### ISSUE TITLE
refresh_token might not work for write requests

### ISSUE THREAD

**Issue by Naokimi** [solidusio-contrib/solidus_bolt#103]
We got the following message on Slack:

> Each refresh token has an expiration of a year, and you can keep using the refresh token for as long as you need. The important note here is that the access tokens granted to you via a refresh token only have view rights. If you need to add an address or a payment method, you must get a brand new authorization code from the shopper and start the oauth dance again.

Haven't confirmed the following yet (need to to QA), but if confirmed it might mean that our implementation doesn't work and we either have to:
- log out the user and have them login again with a Bolt account
- request Bolt to add write permission to the token

**Comment by Naokimi** [comment]
Confirming the above. After waiting 1 hour for the login to pass and going through the order process, the AddAddressService failed with the following error:
```
[ActiveJob] [SolidusBolt::AddAddressJob] [e41f6f8e-4ad5-4a08-bba1-0e34cb6d133f] Error performing SolidusBolt::AddAddressJob (Job ID: e41f6f8e-4ad5-4a08-bba1-0e34cb6d133f) from Async(default) in 1094.51ms: SolidusBolt::ServerError (This action is forbidden.):
/home/naokimi/code/Nebulab/solidus_bolt/app/services/solidus_bolt/base_service.rb:22:in `handle_result'
/home/naokimi/code/Nebulab/solidus_bolt/app/services/solidus_bolt/accounts/add_address_service.rb:37:in `add_address'
/home/naokimi/code/Nebulab/solidus_bolt/app/services/solidus_bolt/accounts/add_address_service.rb:18:in `call'
/home/naokimi/code/Nebulab/solidus_bolt/app/services/solidus_bolt/base_service.rb:14:in `call'
/home/naokimi/code/Nebulab/solidus_bolt/app/jobs/solidus_bolt/add_address_job.rb:6:in `perform'
/home/naokimi/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activejob-6.1.6/lib/active_job/execution.rb:48:in `block in perform_now'
/home/naokimi/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/home/naokimi/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/i18n-1.10.0/lib/i18n.rb:328:in `with_locale'
/home/naokimi/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activejob-6.1.6/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
/home/naokimi/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:126:in `instance_exec'
/home/naokimi/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/home/naokimi/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.6/lib/active_support/core_ext/time/zones.rb:66:in `use_zone'
/home/naokimi/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activejob-6.1.6/lib/active_job/timezones.rb:9:in `block (2 levels) in <module:Timezones>'
/home/naokimi/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:126:in `instance_exec'
/home/naokimi/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/home/naokimi/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activejob-6.1.6/lib/active_job/instrumentation.rb:21:in `block in instrument'
/home/naokimi/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.6/lib/active_support/notifications.rb:203:in `block in instrument'
/home/naokimi/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.6/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/home/naokimi/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.6/lib/active_support/notifications.rb:203:in `instrument'
/home/naokimi/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activejob-6.1.6/lib/active_job/instrumentation.rb:31:in `instrument'
/home/naokimi/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activejob-6.1.6/lib/active_job/instrumentation.rb:14:in `block (2 levels) in <module:Instrumentation>'
/home/naokimi/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:126:in `instance_exec'
/home/naokimi/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/home/naokimi/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activejob-6.1.6/lib/active_job/logging.rb:22:in `block in tag_logger'
/home/naokimi/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.6/lib/active_support/tagged_logging.rb:99:in `block in tagged'
/home/naokimi/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.6/lib/active_support/tagged_logging.rb:37:in `tagged'
/home/naokimi/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.6/lib/active_support/tagged_logging.rb:99:in `tagged'
/home/naokimi/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activejob-6.1.6/lib/active_job/logging.rb:22:in `tag_logger'
/home/naokimi/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activejob-6.1.6/lib/active_job/logging.rb:15:in `block (2 levels) in <module:Logging>'
/home/naokimi/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:126:in `instance_exec'
/home/naokimi/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/home/naokimi/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:137:in `run_callbacks'
/home/naokimi/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activejob-6.1.6/lib/active_job/execution.rb:47:in `perform_now'
/home/naokimi/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activejob-6.1.6/lib/active_job/execution.rb:25:in `block in execute'
/home/naokimi/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/home/naokimi/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activejob-6.1.6/lib/active_job/railtie.rb:47:in `block (4 levels) in <class:Railtie>'
/home/naokimi/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.6/lib/active_support/execution_wrapper.rb:91:in `wrap'
/home/naokimi/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.6/lib/active_support/reloader.rb:72:in `block in wrap'
/home/naokimi/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.6/lib/active_support/execution_wrapper.rb:91:in `wrap'
/home/naokimi/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.6/lib/active_support/reloader.rb:71:in `wrap'
/home/naokimi/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activejob-6.1.6/lib/active_job/railtie.rb:46:in `block (3 levels) in <class:Railtie>'
/home/naokimi/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:126:in `instance_exec'
/home/naokimi/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/home/naokimi/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:137:in `run_callbacks'
/home/naokimi/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activejob-6.1.6/lib/active_job/execution.rb:23:in `execute'
/home/naokimi/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activejob-6.1.6/lib/active_job/queue_adapters/async_adapter.rb:70:in `perform'
/home/naokimi/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:352:in `run_task'
/home/naokimi/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:343:in `block (3 levels) in create_worker'
/home/naokimi/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `loop'
/home/naokimi/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `block (2 levels) in create_worker'
/home/naokimi/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:333:in `catch'
/home/naokimi/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:333:in `block in create_worker'
```
The silver lining is that since it's executed as a Job, it doesn't break the application (and we could add a `rescue`), but this still doesn't solve the fundamental issue about what to do regarding writing with refreshed token.

Please advise

**Comment by Naokimi** [comment]
implementing in https://github.com/solidusio-contrib/solidus_bolt/issues/111
